AllCops:
  NewCops: enable

Style/For:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/MethodLength:
  IgnoredMethods: ['run_intcode']

Metrics/AbcSize:
  IgnoredMethods: ['run_intcode']

Metrics/CyclomaticComplexity:
  IgnoredMethods: ['run_intcode']